#!/usr/bin/env bash

common_command() {
    case "${comando[0]:-}" in
        /start|/Start|/menu|/Menu|/comenzar|/Comenzar) menu_src; return 0 ;;
        /help|/Help|/ayuda|/Ayuda) ayuda_src; return 0 ;;
        /id|/ID) myid_src; return 0 ;;
        /license|/licencia) license_status_src; return 0 ;;
        /install|/instal) link_src; return 0 ;;
        /upgrade|/actualizarhex) upgrade_src; return 0 ;;
    esac
    return 1
}

comand() {
    local command_name="${comando[0]:-}"
    [[ -n "$command_name" ]] || return 0

    common_command && return 0

    case "$actor_role" in
        reseller)
            case "$command_name" in
                /keygen|/Keygen) gerar_key ;;
                /mykeys|/miskeys) access_mykeys ;;
            esac
            ;;
        admin)
            case "$command_name" in
                /keygen|/Keygen) gerar_key ;;
                /mykeys|/miskeys) access_mykeys ;;
                /licenses|/licencias) access_list_licenses ;;
                /revoke|/revocar) access_revoke_license ;;
                /reset|/resetear) access_reset_license ;;
                /addreseller|/addrevendedor) access_add_reseller ;;
                /delreseller|/delrevendedor) access_del_reseller ;;
                /resellers|/revendedores) access_list_resellers ;;
                /allowgroup|/permitirgrupo) access_allow_group ;;
                /delgroup|/eliminargrupo) access_del_group ;;
                /groups|/grupos) access_list_groups ;;
                /api) access_api_status ;;
                /infosys|/sistema) infosys_src ;;
                /update|/actualizar) update ;;
            esac
            ;;
    esac
}
