#!/usr/bin/env bash

myid_src() {
    bot_retorno="<b>IDENTIDAD TELEGRAM</b>\n$LINE\n"
    bot_retorno+="Tu ID: <code>${actor_id}</code>\n"
    bot_retorno+="Chat actual: <code>$(html_escape "$current_chat_id")</code>\n"
    bot_retorno+="Tipo: <b>$(html_escape "$current_chat_type")</b>\n"
    bot_retorno+="Rol: <b>$(html_escape "$actor_role")</b>\n"
    bot_retorno+="$LINE"
    msj_fun
}
