#!/usr/bin/env bash

start_gen() {
    local bot_retorno
    if systemctl is-active --quiet hexgen-http.service; then
        systemctl stop hexgen-http.service
        bot_retorno="$LINE\nServidor de validación: <b>OFFLINE</b>\n$LINE"
    else
        systemctl start hexgen-http.service
        sleep 1
        if systemctl is-active --quiet hexgen-http.service; then
            bot_retorno="$LINE\nServidor de validación: <b>ONLINE</b>\n$LINE"
        else
            bot_retorno="$LINE\nNo se pudo iniciar el servidor. Revisa: journalctl -u hexgen-http.service\n$LINE"
        fi
    fi
    msj_fun
}
